In [4]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:

df=pd.read_csv('/content/drive/MyDrive/layoffs.csv')
df

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0
...,...,...,...,...,...,...,...,...,...
2356,Blackbaud,Charleston,Other,500.0,0.14,NaN,Post-IPO,United States,NaN
2357,Yahoo,SF Bay Area,Consumer,1600.0,0.20,2/9/2023,Acquired,United States,6.0
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0

In [6]:
df.head()

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0

In [7]:
pd.set_option('display.max.rows',7)
# pd.set_option('display.max.columns',10)
# df

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2361 entries, 0 to 2360
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   company                2361 non-null   object
 1   location               2361 non-null   object
 2   industry               2357 non-null   object
 3   total_laid_off         1621 non-null   float64
 4   percentage_laid_off    1576 non-null   float64
 5   date                   2360 non-null   object
 6   stage                  2355 non-null   object
 7   country                2361 non-null   object
 8   funds_raised_millions  2152 non-null   float64
dtypes: float64(3), object(6)
memory usage: 166.1+ KB

In [9]:
df.shape

(2361, 9)

In [10]:
df.tail(2)

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.2,11/28/2022,Unknown,Brazil,260.0

In [11]:
df.head()

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0

In [12]:
df[df['total_laid_off']>10000]

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
281,Google,SF Bay Area,Consumer,12000.0,0.06,1/20/2023,Post-IPO,United States,26.0
749,Meta,SF Bay Area,Consumer,11000.0,0.13,11/9/2022,Post-IPO,United States,26000.0

In [13]:
specific_country=['Brazil','Nepal']
df[df['country'].isin(specific_country)]

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0
13,Ambev Tech,Blumenau,Food,50.0,NaN,3/2/2023,Acquired,Brazil,NaN
20,iFood,Sao Paulo,Food,355.0,0.06,3/1/2023,Subsidiary,Brazil,2100.0
...,...,...,...,...,...,...,...,...,...
2284,Loft,Sao Paulo,Real Estate,47.0,NaN,3/27/2020,Series C,Brazil,263.0
2290,Bcredi,Curitiba,Finance,NaN,NaN,3/27/2020,Series A,Brazil,NaN
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0

In [14]:
df['country']

0           Australia
1       United States
2             Nigeria
            ...
2358           Israel
2359    United States
2360           Brazil
Name: country, Length: 2361, dtype: object

In [15]:
df[df['country'].str.contains('zil')]
#also .str.startswith('a') or endswith

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0
13,Ambev Tech,Blumenau,Food,50.0,NaN,3/2/2023,Acquired,Brazil,NaN
20,iFood,Sao Paulo,Food,355.0,0.06,3/1/2023,Subsidiary,Brazil,2100.0
...,...,...,...,...,...,...,...,...,...
2284,Loft,Sao Paulo,Real Estate,47.0,NaN,3/27/2020,Series C,Brazil,263.0
2290,Bcredi,Curitiba,Finance,NaN,NaN,3/27/2020,Series A,Brazil,NaN
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0

In [16]:
df.set_index('country')

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,funds_raised_millions
country,,,,,,,,
Australia,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,210.0
United States,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,525.0
Nigeria,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,16.0
...,...,...,...,...,...,...,...,...
Israel,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,45.0
United States,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,339.0
Brazil,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,260.0

In [17]:
df.filter(items=['company','location'])

               company       location
0            Atlassian         Sydney
1             SiriusXM  New York City
2               Alerzo         Ibadan
...                ...            ...
2358             Hibob       Tel Aviv
2359            Casper  New York City
2360  Wildlife Studios      Sao Paulo

[2361 rows x 2 columns]

In [18]:
# df.reset_index(drop=True)

In [19]:
df.loc[0]

company                  Atlassian
location                    Sydney
industry                     Other
                           ...
stage                     Post-IPO
country                  Australia
funds_raised_millions        210.0
Name: 0, Length: 9, dtype: object

In [20]:
df.loc[1,'country']

'United States'

In [21]:
df.iloc[3]

company                     UpGrad
location                    Mumbai
industry                 Education
                           ...
stage                      Unknown
country                      India
funds_raised_millions        631.0
Name: 3, Length: 9, dtype: object

In [22]:
df

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
...,...,...,...,...,...,...,...,...,...
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0

In [23]:
df[df['total_laid_off']<10].sort_values('total_laid_off')

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
1836,Branch,New York City,Retail,3.0,0.27,6/11/2020,Seed,United States,2.0
2348,Flytedesk,Boulder,Marketing,4.0,0.20,3/18/2020,Seed,United States,4.0
2126,Spyce,Boston,Food,4.0,0.12,4/8/2020,Series A,United States,26.0
...,...,...,...,...,...,...,...,...,...
1431,BitOasis,Dubai,Crypto,9.0,0.05,6/19/2022,Series B,United Arab Emirates,30.0
2228,Incredible Health,SF Bay Area,Healthcare,9.0,0.40,4/1/2020,Series A,United States,15.0
2262,Iris Nova,New York City,Food,9.0,0.50,3/30/2020,Seed,United States,15.0

In [24]:
df[df['total_laid_off']<10].sort_values(by=['total_laid_off','industry'],ascending=False)
# total lais of is written forst so it organixe that first

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
677,&Open,Dublin,Marketing,9.0,0.09,11/17/2022,Series A,Ireland,35.0
2228,Incredible Health,SF Bay Area,Healthcare,9.0,0.40,4/1/2020,Series A,United States,15.0
2262,Iris Nova,New York City,Food,9.0,0.50,3/30/2020,Seed,United States,15.0
...,...,...,...,...,...,...,...,...,...
2126,Spyce,Boston,Food,4.0,0.12,4/8/2020,Series A,United States,26.0
2000,TutorMundi,Sao Paulo,Education,4.0,1.00,4/24/2020,Series A,Brazil,2.0
1836,Branch,New York City,Retail,3.0,0.27,6/11/2020,Seed,United States,2.0

In [25]:
df['country'].sort_values()

1571    Argentina
641     Argentina
352     Argentina
          ...
1500      Vietnam
980       Vietnam
1910      Vietnam
Name: country, Length: 2361, dtype: object

In [26]:
df[df['total_laid_off']<10].sort_values(by=['country','industry'],ascending=[True,False])

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
1102,Expert360,Sydney,Recruiting,7.0,NaN,8/11/2022,Series C,Australia,26.0
71,Kinde,Sydney,Other,8.0,0.28,2/20/2023,Seed,Australia,10.0
2000,TutorMundi,Sao Paulo,Education,4.0,1.00,4/24/2020,Series A,Brazil,2.0
...,...,...,...,...,...,...,...,...,...
1806,Havenly,Denver,Consumer,5.0,NaN,7/1/2020,Series C,United States,57.8
1999,Jiobit,Chicago,Consumer,6.0,0.21,4/24/2020,Unknown,United States,12.0
2353,Panda Squad,SF Bay Area,Consumer,6.0,0.75,3/13/2020,Seed,United States,1.0

INDEXeing

In [27]:
df1 = pd.read_csv('/content/drive/MyDrive/world_population.csv',index_col='Country')
#each country is unique so great index
df1

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [28]:
df1.loc['Albania']
#df1.loc[1]

Rank                               138
CCA3                               ALB
Capital                         Tirana
                                ...
Density (per km²)              98.8702
Growth Rate                     0.9957
World Population Percentage       0.04
Name: Albania, Length: 16, dtype: object

In [29]:
df1 = df1.reset_index()
df1 = df1.set_index(['Continent','Country'])
df1.sort_index(level='Continent')

                         Rank CCA3     Capital  2022 Population  \
Continent     Country
Africa        Algeria      34  DZA     Algiers       44903225.0
              Angola       42  AGO      Luanda       35588987.0
              Benin        77  BEN  Porto-Novo       13352864.0
...                       ...  ...         ...              ...
South America Suriname    170  SUR  Paramaribo         618040.0
              Uruguay     133  URY  Montevideo        3422794.0
              Venezuela    51  VEN     Caracas       28301696.0

                         2020 Population  2015 Population  2010 Population  \
Continent     Country
Africa        Algeria         43451666.0       39543154.0       35856344.0
              Angola          33428485.0       28127721.0       23364185.0
              Benin           12643123.0       10932783.0        9445710.0
...                                  ...              ...              ...
South America Suriname          607065.0         575475.0         546080.0
              Uruguay          3429086.0        3402818.0        3352651.0
              Venezuela       28490453.0       30529716.0       28715022.0

                         2000 Population  1990 Population  1980 Population  \
Continent     Country
Africa        Algeria         30774621.0       25518074.0       18739378.0
              Angola          16394062.0       11828638.0        8330047.0
              Benin            6998023.0        5133419.0        3833939.0
...                                  ...              ...              ...
South America Suriname          478998.0         412756.0         375112.0
              Uruguay          3292224.0        3117012.0        2953750.0
              Venezuela              NaN       19750579.0       15210443.0

                         1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
Africa        Algeria         13795915.0   2381741.0            18.8531
              Angola           6029700.0   1246700.0            28.5466
              Benin            3023443.0    112622.0           118.5635
...                                  ...         ...                ...
South America Suriname          379918.0    163820.0             3.7727
              Uruguay          2790265.0    181034.0            18.9069
              Venezuela       11355475.0         NaN            30.8820

                         Growth Rate  World Population Percentage
Continent     Country
Africa        Algeria         1.0164                         0.56
              Angola          1.0315                         0.45
              Benin           1.0274                         0.17
...                              ...                          ...
South America Suriname        1.0082                         0.01
              Uruguay         0.9990                         0.04
              Venezuela       1.0036                         0.35

[234 rows x 15 columns]

In [30]:
df1.sort_index(level='Country',ascending=False)

                       Rank CCA3  Capital  2022 Population  2020 Population  \
Continent Country
Africa    Zimbabwe       74  ZWE   Harare       16320537.0       15669666.0
          Zambia         63  ZMB   Lusaka       20017675.0       18927715.0
Asia      Yemen          46  YEM    Sanaa       33696614.0       32284046.0
...                     ...  ...      ...              ...              ...
Africa    Algeria        34  DZA  Algiers       44903225.0       43451666.0
Europe    Albania       138  ALB   Tirana        2842321.0        2866849.0
Asia      Afghanistan    36  AFG    Kabul       41128771.0       38972230.0

                       2015 Population  2010 Population  2000 Population  \
Continent Country
Africa    Zimbabwe          14154937.0       12839771.0       11834676.0
          Zambia                   NaN       13792086.0        9891136.0
Asia      Yemen             28516545.0       24743946.0       18628700.0
...                                ...              ...              ...
Africa    Algeria           39543154.0       35856344.0       30774621.0
Europe    Albania            2882481.0        2913399.0        3182021.0
Asia      Afghanistan       33753499.0       28189672.0       19542982.0

                       1990 Population  1980 Population  1970 Population  \
Continent Country
Africa    Zimbabwe          10113893.0        7049926.0        5202918.0
          Zambia             7686401.0        5720438.0        4281671.0
Asia      Yemen             13375121.0        9204938.0        6843607.0
...                                ...              ...              ...
Africa    Algeria           25518074.0       18739378.0       13795915.0
Europe    Albania            3295066.0        2941651.0        2324731.0
Asia      Afghanistan       10694796.0       12486631.0       10752971.0

                       Area (km²)  Density (per km²)  Growth Rate  \
Continent Country
Africa    Zimbabwe       390757.0            41.7665       1.0204
          Zambia         752612.0            26.5976       1.0280
Asia      Yemen          527968.0            63.8232       1.0217
...                           ...                ...          ...
Africa    Algeria       2381741.0            18.8531       1.0164
Europe    Albania         28748.0            98.8702       0.9957
Asia      Afghanistan    652230.0            63.0587       1.0257

                       World Population Percentage
Continent Country
Africa    Zimbabwe                            0.20
          Zambia                              0.25
Asia      Yemen                               0.42
...                                            ...
Africa    Algeria                             0.56
Europe    Albania                             0.04
Asia      Afghanistan                         0.52

[234 rows x 15 columns]

In [31]:
df1.sort_index(ascending=[False,True])

                              Rank CCA3       Capital  2022 Population  \
Continent     Country
South America Argentina         33  ARG  Buenos Aires       45510318.0
              Bolivia           80  BOL         Sucre       12224110.0
              Brazil             7  BRA      Brasilia      215313498.0
...                            ...  ...           ...              ...
Africa        Western Sahara   172  ESH      El Aaiún         575986.0
              Zambia            63  ZMB        Lusaka       20017675.0
              Zimbabwe          74  ZWE        Harare       16320537.0

                              2020 Population  2015 Population  \
Continent     Country
South America Argentina            45036032.0       43257065.0
              Bolivia              11936162.0       11090085.0
              Brazil              213196304.0      205188205.0
...                                       ...              ...
Africa        Western Sahara         556048.0         491824.0
              Zambia               18927715.0              NaN
              Zimbabwe             15669666.0       14154937.0

                              2010 Population  2000 Population  \
Continent     Country
South America Argentina            41100123.0       37070774.0
              Bolivia              10223270.0        8592656.0
              Brazil              196353492.0      175873720.0
...                                       ...              ...
Africa        Western Sahara         413296.0         270375.0
              Zambia               13792086.0        9891136.0
              Zimbabwe             12839771.0       11834676.0

                              1990 Population  1980 Population  \
Continent     Country
South America Argentina            32637657.0       28024803.0
              Bolivia               7096194.0        5736088.0
              Brazil              150706446.0      122288383.0
...                                       ...              ...
Africa        Western Sahara         178529.0         116775.0
              Zambia                7686401.0        5720438.0
              Zimbabwe             10113893.0        7049926.0

                              1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
South America Argentina            23842803.0   2780400.0            16.3683
              Bolivia               4585693.0   1098581.0            11.1272
              Brazil               96369875.0   8515767.0            25.2841
...                                       ...         ...                ...
Africa        Western Sahara          76371.0    266000.0             2.1654
              Zambia                4281671.0    752612.0            26.5976
              Zimbabwe              5202918.0    390757.0            41.7665

                              Growth Rate  World Population Percentage
Continent     Country
South America Argentina            1.0052                         0.57
              Bolivia              1.0120                         0.15
              Brazil               1.0046                         2.70
...                                   ...                          ...
Africa        Western Sahara       1.0184                         0.01
              Zambia               1.0280                         0.25
              Zimbabwe             1.0204                         0.20

[234 rows x 15 columns]

In [32]:
df1.loc['Africa']
#search only first index which is continent

,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,
Algeria,34,DZA,Algiers,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
Angola,42,AGO,Luanda,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
Benin,77,BEN,Porto-Novo,13352864.0,12643123.0,10932783.0,9445710.0,6998023.0,5133419.0,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Western Sahara,172,ESH,El Aaiún,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Zambia,63,ZMB,Lusaka,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [33]:
df1.loc['Africa','Capital']

Country
Algeria              Algiers
Angola                Luanda
Benin             Porto-Novo
                     ...
Western Sahara      El Aaiún
Zambia                Lusaka
Zimbabwe              Harare
Name: Capital, Length: 57, dtype: object

group by and aggregating

In [52]:
abc=df.groupby('company')

In [53]:
abc.mean(numeric_only=True)

                  total_laid_off  percentage_laid_off  funds_raised_millions
company
 E Inc.                      NaN                  NaN                    NaN
 Included Health             NaN                 0.06                  272.0
#Paid                       19.0                 0.17                   21.0
...                          ...                  ...                    ...
nCino                      100.0                 0.07                 1100.0
tZero                        NaN                  NaN                  472.0
uShip                       65.0                 0.37                   69.0

[1893 rows x 3 columns]

In [56]:
df.groupby('country').mean(numeric_only=True)

                total_laid_off  percentage_laid_off  funds_raised_millions
country
Argentina            64.600000             0.227500             718.000000
Australia            83.000000             0.385000             106.217391
Austria             190.000000             0.270000             639.333333
...                        ...                  ...                    ...
United States.      561.666667             0.095000            1290.250000
Uruguay                    NaN                  NaN               1.800000
Vietnam                    NaN             0.833333              22.333333

[60 rows x 3 columns]

In [57]:
df.groupby('country').count()

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,funds_raised_millions
country,,,,,,,,
Argentina,6,6,6,5,4,6,6,4
Australia,54,54,54,28,38,54,54,46
Austria,3,3,3,3,1,3,3,3
...,...,...,...,...,...,...,...,...
United States.,4,4,4,3,2,4,4,4
Uruguay,1,1,1,0,0,1,1,1
Vietnam,3,3,3,0,3,3,3,3

In [60]:
df.groupby('country').min(numeric_only=True)

                total_laid_off  percentage_laid_off  funds_raised_millions
country
Argentina                 40.0                 0.03                   11.0
Australia                  7.0                 0.05                    1.0
Austria                  100.0                 0.27                  546.0
...                        ...                  ...                    ...
United States.            75.0                 0.02                  347.0
Uruguay                    NaN                  NaN                    1.8
Vietnam                    NaN                 0.50                    1.0

[60 rows x 3 columns]

In [62]:
df.groupby('country').sum(numeric_only=True)

                total_laid_off  percentage_laid_off  funds_raised_millions
country
Argentina                323.0                 0.91                 2872.0
Australia               2324.0                14.63                 4886.0
Austria                  570.0                 0.27                 1918.0
...                        ...                  ...                    ...
United States.          1685.0                 0.19                 5161.0
Uruguay                    0.0                 0.00                    1.8
Vietnam                    0.0                 2.50                   67.0

[60 rows x 3 columns]

In [66]:
df.groupby(['country','industry']).mean(numeric_only=True)

                          total_laid_off  percentage_laid_off  \
country   industry
Argentina Crypto                    90.0                0.415
          Finance                   53.0                0.030
          Food                       NaN                  NaN
...                                  ...                  ...
Uruguay   Transportation             NaN                  NaN
Vietnam   Fitness                    NaN                1.000
          Real Estate                NaN                0.750

                          funds_raised_millions
country   industry
Argentina Crypto                           14.0
          Finance                         544.0
          Food                           2300.0
...                                         ...
Uruguay   Transportation                    1.8
Vietnam   Fitness                           1.0
          Real Estate                      33.0

[305 rows x 3 columns]

In [67]:
df.groupby('country').agg({'total_laid_off': ['mean', 'max','count','min'], 'industry': 'count'})

               total_laid_off                      industry
                         mean     max count    min    count
country
Argentina           64.600000   100.0     5   40.0        6
Australia           83.000000   500.0    28    7.0       54
Austria            190.000000   270.0     3  100.0        3
...                       ...     ...   ...    ...      ...
United States.     561.666667  1500.0     3   75.0        4
Uruguay                   NaN     NaN     0    NaN        1
Vietnam                   NaN     NaN     0    NaN        3

[60 rows x 5 columns]

In [68]:
df.groupby('country').describe()
#shortcut

               total_laid_off                                               \
                        count        mean         std    min    25%    50%
country
Argentina                 5.0   64.600000   24.714368   40.0   50.0   53.0
Australia                28.0   83.000000   99.663508    7.0   30.0   64.5
Austria                   3.0  190.000000   85.440037  100.0  150.0  200.0
...                       ...         ...         ...    ...    ...    ...
United States.            3.0  561.666667  812.808916   75.0   92.5  110.0
Uruguay                   0.0         NaN         NaN    NaN    NaN    NaN
Vietnam                   0.0         NaN         NaN    NaN    NaN    NaN

                               percentage_laid_off            ...          \
                   75%     max               count      mean  ...     75%
country                                                       ...
Argentina        80.00   100.0                 4.0  0.227500  ...  0.3975
Australia        99.25   500.0                38.0  0.385000  ...  0.5000
Austria         235.00   270.0                 1.0  0.270000  ...  0.2700
...                ...     ...                 ...       ...  ...     ...
United States.  805.00  1500.0                 2.0  0.095000  ...  0.1325
Uruguay            NaN     NaN                 0.0       NaN  ...     NaN
Vietnam            NaN     NaN                 3.0  0.833333  ...  1.0000

                     funds_raised_millions                                   \
                 max                 count         mean          std    min
country
Argentina       0.45                   4.0   718.000000  1083.858847   11.0
Australia       1.00                  46.0   106.217391   251.875094    1.0
Austria         0.27                   3.0   639.333333    80.829038  546.0
...              ...                   ...          ...          ...    ...
United States.  0.17                   4.0  1290.250000  1194.211700  347.0
Uruguay          NaN                   1.0     1.800000          NaN    1.8
Vietnam         1.00                   3.0    22.333333    18.475209    1.0


                   25%    50%      75%     max
country
Argentina        15.50  280.5   983.00  2300.0
Australia        15.75   43.0    97.25  1700.0
Austria         616.00  686.0   686.00   686.0
...                ...    ...      ...     ...
United States.  547.25  907.0  1650.00  3000.0
Uruguay           1.80    1.8     1.80     1.8
Vietnam          17.00   33.0    33.00    33.0

[60 rows x 24 columns]

In [69]:
df.describe()

       total_laid_off  percentage_laid_off  funds_raised_millions
count     1621.000000          1576.000000            2152.000000
mean       238.358421             0.257917             822.454134
std        769.718801             0.255575            5593.961626
...               ...                  ...                    ...
50%         80.000000             0.170000             156.500000
75%        180.000000             0.300000             445.000000
max      12000.000000             1.000000          121900.000000

[8 rows x 3 columns]

merge join and concatenate

In [75]:
df_products = pd.DataFrame({
    'product_id': [101, 102, 103, 104, 105],
    'product_name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
    'price': [1200, 25, 75, 300, 50]
})
data_sales = {
    'sale_id': [1, 2, 3, 4, 5, 6],
    'product_id': [101, 103, 102, 106, 101, 107], # 106 and 107 are new products not in df_products
    'quantity': [1, 2, 1, 3, 1, 1],
    'sale_date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06']
}
df_sales = pd.DataFrame(data_sales)

# Save DataFrames to CSV files in Google Drive
df_products.to_csv('/content/drive/MyDrive/products.csv', index=False)
df_sales.to_csv('/content/drive/MyDrive/sales.csv', index=False)

In [76]:
df_sales

   sale_id  product_id  quantity   sale_date
0        1         101         1  2023-01-01
1        2         103         2  2023-01-02
2        3         102         1  2023-01-03
3        4         106         3  2023-01-04
4        5         101         1  2023-01-05
5        6         107         1  2023-01-06

In [77]:
df_products

   product_id product_name  price
0         101       Laptop   1200
1         102        Mouse     25
2         103     Keyboard     75
3         104      Monitor    300
4         105       Webcam     50

In [78]:
df_products.merge(df_sales)
#inner join (checks similar columns and combines it)

   product_id product_name  price  sale_id  quantity   sale_date
0         101       Laptop   1200        1         1  2023-01-01
1         101       Laptop   1200        5         1  2023-01-05
2         102        Mouse     25        3         1  2023-01-03
3         103     Keyboard     75        2         2  2023-01-02

In [80]:
df_products.merge(df_sales,how='left')

   product_id product_name  price  sale_id  quantity   sale_date
0         101       Laptop   1200      1.0       1.0  2023-01-01
1         101       Laptop   1200      5.0       1.0  2023-01-05
2         102        Mouse     25      3.0       1.0  2023-01-03
3         103     Keyboard     75      2.0       2.0  2023-01-02
4         104      Monitor    300      NaN       NaN         NaN
5         105       Webcam     50      NaN       NaN         NaN

In [81]:
df_products.merge(df_sales,how='right')
#right join

   product_id product_name   price  sale_id  quantity   sale_date
0         101       Laptop  1200.0        1         1  2023-01-01
1         103     Keyboard    75.0        2         2  2023-01-02
2         102        Mouse    25.0        3         1  2023-01-03
3         106          NaN     NaN        4         3  2023-01-04
4         101       Laptop  1200.0        5         1  2023-01-05
5         107          NaN     NaN        6         1  2023-01-06

In [82]:
df_products.merge(df_sales,how='outer')
#outer join gives every thing of both dataframes

    product_id product_name   price  sale_id  quantity   sale_date
0          101       Laptop  1200.0      1.0       1.0  2023-01-01
1          101       Laptop  1200.0      5.0       1.0  2023-01-05
2          102        Mouse    25.0      3.0       1.0  2023-01-03
..         ...          ...     ...      ...       ...         ...
5          105       Webcam    50.0      NaN       NaN         NaN
6          106          NaN     NaN      4.0       3.0  2023-01-04
7          107          NaN     NaN      6.0       1.0  2023-01-06

[8 rows x 6 columns]

In [83]:
df_products.merge(df_sales,how='cross')
#takes one rown and check with all the provided ones

,product_id_x,product_name,price,sale_id,product_id_y,quantity,sale_date
0,101,Laptop,1200,1,101,1,2023-01-01
1,101,Laptop,1200,2,103,2,2023-01-02
2,101,Laptop,1200,3,102,1,2023-01-03
...,...,...,...,...,...,...,...
27,105,Webcam,50,4,106,3,2023-01-04
28,105,Webcam,50,5,101,1,2023-01-05
29,105,Webcam,50,6,107,1,2023-01-06

In [84]:
df_products.join(df_sales.set_index('product_id'),on='product_id')
#similar indexes can be combined together form join
#if both tables had diff ids then
#df.merge(df1, left_on='id', right_on='emp_id')

   product_id product_name  price  sale_id  quantity   sale_date
0         101       Laptop   1200      1.0       1.0  2023-01-01
0         101       Laptop   1200      5.0       1.0  2023-01-05
1         102        Mouse     25      3.0       1.0  2023-01-03
2         103     Keyboard     75      2.0       2.0  2023-01-02
3         104      Monitor    300      NaN       NaN         NaN
4         105       Webcam     50      NaN       NaN         NaN

In [85]:
df_products.set_index('product_id').join(df_sales.set_index('product_id'))
# similar to join on e.id=s.id on sql (can stil do how= 'left right etc') use merge cuz more simpler

           product_name  price  sale_id  quantity   sale_date
product_id
101              Laptop   1200      1.0       1.0  2023-01-01
101              Laptop   1200      5.0       1.0  2023-01-05
102               Mouse     25      3.0       1.0  2023-01-03
103            Keyboard     75      2.0       2.0  2023-01-02
104             Monitor    300      NaN       NaN         NaN
105              Webcam     50      NaN       NaN         NaN

concatenate

In [87]:
pd.concat([df_products, df_sales])
# top 7 rows are from products and remailing bottom form sales

    product_id product_name   price  sale_id  quantity   sale_date
0          101       Laptop  1200.0      NaN       NaN         NaN
1          102        Mouse    25.0      NaN       NaN         NaN
2          103     Keyboard    75.0      NaN       NaN         NaN
..         ...          ...     ...      ...       ...         ...
3          106          NaN     NaN      4.0       3.0  2023-01-04
4          101          NaN     NaN      5.0       1.0  2023-01-05
5          107          NaN     NaN      6.0       1.0  2023-01-06

[11 rows x 6 columns]

In [90]:
pd.concat([df_products, df_sales], join='inner')
#only concat common columns

    product_id
0          101
1          102
2          103
..         ...
3          106
4          101
5          107

[11 rows x 1 columns]

In [ ]:
df_products.append(df_sales)
# this used to do same thing as concat but does not work anymore